In [1]:
!pwd

/Users/miguelcamargorojas/Documents/UP/NLP-Ago-dic24/Semana II


In [2]:
!ls sample_data

ls: sample_data: No such file or directory


In [3]:
!python3 -V

Python 3.11.6


In [4]:
!python3 -m pip install numpy pandas


[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python3.11 -m pip install --upgrade pip


In [5]:
!python3 -m pip list

Package                      Version
---------------------------- ---------
absl-py                      2.0.0
appnope                      0.1.3
asttokens                    2.2.1
astunparse                   1.6.3
backcall                     0.2.0
cachetools                   5.3.1
certifi                      2023.7.22
cffi                         1.16.0
charset-normalizer           3.2.0
comm                         0.1.3
debugpy                      1.6.7
decorator                    5.1.1
docutils                     0.20.1
executing                    1.2.0
flatbuffers                  23.5.26
gast                         0.5.4
google-auth                  2.23.2
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
grpcio                       1.58.0
h5py                         3.9.0
idna                         3.4
ipykernel                    6.23.1
ipython                      8.13.2
jedi                         0.18.2
jupyter_client               8.2.0
jup

In [6]:
import numpy as np
import pandas as pd

# Repaso de numpy

In [7]:
lista = [1, 1.1, True, "", [], (), {}]

In [8]:
type(lista)

list

In [9]:
list(range(0, 10, 1))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
np.arange(1, 10, .5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [11]:
arreglo1 = np.arange(1, 10, .5)

In [12]:
dir(arreglo1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [13]:
np.asarray([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [14]:
lista_de_listas = [[1, 2, 3], [4, 5, 6]]

In [15]:
len(lista_de_listas)

2

In [16]:
lista_de_listas[0][0]

1

In [17]:
arr = np.asarray(lista_de_listas)

In [18]:
type(arr)

numpy.ndarray

In [19]:
len(arr)

2

In [20]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr.shape

(2, 3)

In [22]:
arr.dtype

dtype('int64')

In [23]:
arr.size

6

In [24]:
arr.reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
arr.reshape((6, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [26]:
arr.reshape((1, 6))

array([[1, 2, 3, 4, 5, 6]])

In [27]:
np.random.random(10)

array([0.34656652, 0.06241988, 0.70772838, 0.73985674, 0.03172282,
       0.28603272, 0.0354376 , 0.58282877, 0.97048232, 0.1867636 ])

In [28]:
np.random.seed(1)

In [29]:
np.random.random(10)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
       3.96767474e-01, 5.38816734e-01])

In [30]:
np.random.randint(0, 101, size=(10, 10))

array([[ 18,  84,  11,  28,  29,  14,  50,  68,  87,  87],
       [ 94,  96,  86,  13,   9,   7,  63,  61,  22,  57],
       [  1,   0,  60,  81,   8,  88,  13,  47,  72,  30],
       [ 71,   3,  70,  21,  49,  57,   3,  68,  24,  43],
       [ 76,  26,  52,  80,  41,  82,  15,  64,  68,  25],
       [ 98,  87,   7,  26,  25,  22,   9,  67,  23, 100],
       [ 27,  37,  57,  83,  38,   8,  32,  34,  10,  23],
       [ 15,  87,  25,  71,  92,  74,  62,  46,  32,  88],
       [ 23,  55,  65,  77,   3,   0,  77,   6,  52,  85],
       [ 70,   2,  76,  91,  21,  75,   7,  77,  72,  75]])

In [31]:
np.zeros((5, 5), dtype=np.int32)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [32]:
np.ones((5, 5), dtype=np.int32)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [33]:
arr2 = np.random.randint(0, 101, size=(10, 10))

In [34]:
arr2

array([[76, 43, 20, 30, 36,  7, 45, 68, 57, 82],
       [96, 13, 10, 23, 81,  7, 24, 74, 92, 20],
       [32, 12, 65, 94, 60, 24, 82, 97,  2, 92],
       [98, 10, 54, 96, 82, 86, 70, 66, 71, 48],
       [54, 15,  5, 17, 42, 20, 48, 22, 13, 97],
       [53, 84, 10, 96, 55, 61, 56, 89, 21, 96],
       [83, 25, 14, 13, 84, 43,  6, 77, 56, 59],
       [15, 24,  9, 66, 71, 53, 69, 36, 21, 40],
       [77, 91, 49, 47, 77, 40, 78, 45, 87, 16],
       [28, 45, 67, 66, 78, 46,  0, 29, 63, 75]])

In [35]:
arr2.shape

(10, 10)

In [36]:
arr2[0, 0]

76

In [37]:
arr2[4:, 4:]

array([[42, 20, 48, 22, 13, 97],
       [55, 61, 56, 89, 21, 96],
       [84, 43,  6, 77, 56, 59],
       [71, 53, 69, 36, 21, 40],
       [77, 40, 78, 45, 87, 16],
       [78, 46,  0, 29, 63, 75]])

In [38]:
arr2.min()

0

In [39]:
arr2.max()

98

In [40]:
arr2

array([[76, 43, 20, 30, 36,  7, 45, 68, 57, 82],
       [96, 13, 10, 23, 81,  7, 24, 74, 92, 20],
       [32, 12, 65, 94, 60, 24, 82, 97,  2, 92],
       [98, 10, 54, 96, 82, 86, 70, 66, 71, 48],
       [54, 15,  5, 17, 42, 20, 48, 22, 13, 97],
       [53, 84, 10, 96, 55, 61, 56, 89, 21, 96],
       [83, 25, 14, 13, 84, 43,  6, 77, 56, 59],
       [15, 24,  9, 66, 71, 53, 69, 36, 21, 40],
       [77, 91, 49, 47, 77, 40, 78, 45, 87, 16],
       [28, 45, 67, 66, 78, 46,  0, 29, 63, 75]])

In [41]:
arr2.min(axis=0) # axis=0 pregunta por columna

array([15, 10,  5, 13, 36,  7,  0, 22,  2, 16])

In [42]:
arr2.min(axis=1) # axis=1 pregunta por fila

array([ 7,  7,  2, 10,  5, 10,  6,  9, 16,  0])

In [43]:
arr2.mean() # Promedio

50.67

In [44]:
arr2.std()

29.15477833906477

In [45]:
np.median(arr2)

53.0

Operaciones con arreglos

In [46]:
arr2 + 1

array([[77, 44, 21, 31, 37,  8, 46, 69, 58, 83],
       [97, 14, 11, 24, 82,  8, 25, 75, 93, 21],
       [33, 13, 66, 95, 61, 25, 83, 98,  3, 93],
       [99, 11, 55, 97, 83, 87, 71, 67, 72, 49],
       [55, 16,  6, 18, 43, 21, 49, 23, 14, 98],
       [54, 85, 11, 97, 56, 62, 57, 90, 22, 97],
       [84, 26, 15, 14, 85, 44,  7, 78, 57, 60],
       [16, 25, 10, 67, 72, 54, 70, 37, 22, 41],
       [78, 92, 50, 48, 78, 41, 79, 46, 88, 17],
       [29, 46, 68, 67, 79, 47,  1, 30, 64, 76]])

In [47]:
arr2 ** 2

array([[5776, 1849,  400,  900, 1296,   49, 2025, 4624, 3249, 6724],
       [9216,  169,  100,  529, 6561,   49,  576, 5476, 8464,  400],
       [1024,  144, 4225, 8836, 3600,  576, 6724, 9409,    4, 8464],
       [9604,  100, 2916, 9216, 6724, 7396, 4900, 4356, 5041, 2304],
       [2916,  225,   25,  289, 1764,  400, 2304,  484,  169, 9409],
       [2809, 7056,  100, 9216, 3025, 3721, 3136, 7921,  441, 9216],
       [6889,  625,  196,  169, 7056, 1849,   36, 5929, 3136, 3481],
       [ 225,  576,   81, 4356, 5041, 2809, 4761, 1296,  441, 1600],
       [5929, 8281, 2401, 2209, 5929, 1600, 6084, 2025, 7569,  256],
       [ 784, 2025, 4489, 4356, 6084, 2116,    0,  841, 3969, 5625]])

## Copiar arreglos

In [54]:
arr1 = np.array(range(10))

In [55]:
# Copiar 
tmp = arr1

In [57]:
print(arr1, tmp)

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9]


In [58]:
arr1[0] = 100

In [59]:
print(arr1, tmp)

[100   1   2   3   4   5   6   7   8   9] [100   1   2   3   4   5   6   7   8   9]


In [60]:
arr1 = np.array(range(10))
tmp = arr1.copy()

In [61]:
print(arr1, tmp)

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9]


In [62]:
arr1[-1] = 100

In [63]:
print(arr1, tmp)

[  0   1   2   3   4   5   6   7   8 100] [0 1 2 3 4 5 6 7 8 9]


# Pandas

In [64]:
serie1 = pd.Series(range(1, 11))

In [65]:
type(serie1)

pandas.core.series.Series

In [51]:
dir(serie1)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__bool__',
 '__class__',
 '__column_consortium_standard__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__

In [66]:
serie1

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [68]:
serie1[9]

10

In [71]:
serie1[5:7]

5    6
6    7
dtype: int64

In [72]:
serie1 + 10

0    11
1    12
2    13
3    14
4    15
5    16
6    17
7    18
8    19
9    20
dtype: int64

In [74]:
serie1 ** 2

0      1
1      4
2      9
3     16
4     25
5     36
6     49
7     64
8     81
9    100
dtype: int64

In [73]:
serie1

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [76]:
# Copiado de Series
serie2 = serie1
print(serie1, "\n" , serie2)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64 
 0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64


In [77]:
serie1[0] = 200
print(serie1, "\n" , serie2)

0    200
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
dtype: int64 
 0    200
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
dtype: int64


In [78]:
serie2 = serie1.copy()
serie1[-1] = 500
print(serie1, "\n" , serie2)

 0    200
 1      2
 2      3
 3      4
 4      5
 5      6
 6      7
 7      8
 8      9
 9     10
-1    500
dtype: int64 
 0    200
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
dtype: int64


In [79]:
def f(x):
    if x % 2 == 0:
        return 100
    else:
        return None

In [81]:
serie1.apply(f)

 0    100.0
 1    100.0
 2      NaN
 3    100.0
 4      NaN
 5    100.0
 6      NaN
 7    100.0
 8      NaN
 9    100.0
-1    100.0
dtype: float64

In [82]:
serie1.apply(np.math.sqrt)

/var/folders/vr/9n_h2gsj7m16qv6j55xbdp2m0000gn/T/ipykernel_12780/3679405196.py:1: DeprecationWarning: `np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`
  serie1.apply(np.math.sqrt)


 0    14.142136
 1     1.414214
 2     1.732051
 3     2.000000
 4     2.236068
 5     2.449490
 6     2.645751
 7     2.828427
 8     3.000000
 9     3.162278
-1    22.360680
dtype: float64

In [83]:
import math

In [84]:
serie1.apply(math.sqrt)

 0    14.142136
 1     1.414214
 2     1.732051
 3     2.000000
 4     2.236068
 5     2.449490
 6     2.645751
 7     2.828427
 8     3.000000
 9     3.162278
-1    22.360680
dtype: float64

### pd.DataFrame

In [124]:
dir(pd.DataFrame())

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__r

In [86]:
pd.Series(range(1, 11))

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [126]:
df = pd.DataFrame(range(1, 11), columns=("valores", ))

In [94]:
df

valores
0        1
1        2
2        3
3        4
4        5
5        6
6        7
7        8
8        9
9       10

In [92]:
type(df)

pandas.core.frame.DataFrame

In [97]:
df["valores"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: valores, dtype: int64

In [98]:
df["hola"]

KeyError: 'hola'

In [96]:
# No ocupamos index, ocupamos llave
type(df["valores"])

pandas.core.series.Series

In [127]:
df["val_mas1"] = df["valores"] + 1

In [103]:
df

valores  val_mas1
0        1         2
1        2         3
2        3         4
3        4         5
4        5         6
5        6         7
6        7         8
7        8         9
8        9        10
9       10        11

In [128]:
df["val_log"] = df["valores"].apply(math.log)

In [113]:
df

valores  val_mas1   val_log
0        1         2  0.000000
1        2         3  0.693147
2        3         4  1.098612
3        4         5  1.386294
4        5         6  1.609438
5        6         7  1.791759
6        7         8  1.945910
7        8         9  2.079442
8        9        10  2.197225
9       10        11  2.302585

In [107]:
df["val_mas1"] + 1

0     3
1     4
2     5
3     6
4     7
5     8
6     9
7    10
8    11
9    12
Name: val_mas1, dtype: int64

In [110]:
# Quitar columnas
del df["val_log"] 

In [116]:
df

valores  val_mas1   val_log
0        1         2  0.000000
1        2         3  0.693147
2        3         4  1.098612
3        4         5  1.386294
4        5         6  1.609438
5        6         7  1.791759
6        7         8  1.945910
7        8         9  2.079442
8        9        10  2.197225
9       10        11  2.302585

In [120]:
df = df.drop(columns="valores")

In [121]:
df

val_mas1   val_log
0         2  0.000000
1         3  0.693147
2         4  1.098612
3         5  1.386294
4         6  1.609438
5         7  1.791759
6         8  1.945910
7         9  2.079442
8        10  2.197225
9        11  2.302585

In [122]:
df.drop(columns="val_mas1", inplace=True)

In [123]:
df

val_log
0  0.000000
1  0.693147
2  1.098612
3  1.386294
4  1.609438
5  1.791759
6  1.945910
7  2.079442
8  2.197225
9  2.302585

In [129]:
df

valores  val_mas1   val_log
0        1         2  0.000000
1        2         3  0.693147
2        3         4  1.098612
3        4         5  1.386294
4        5         6  1.609438
5        6         7  1.791759
6        7         8  1.945910
7        8         9  2.079442
8        9        10  2.197225
9       10        11  2.302585

In [130]:
len(df) # Devuelve cantidad de filas

10

In [134]:
df.head(-1)

valores  val_mas1   val_log
0        1         2  0.000000
1        2         3  0.693147
2        3         4  1.098612
3        4         5  1.386294
4        5         6  1.609438
5        6         7  1.791759
6        7         8  1.945910
7        8         9  2.079442
8        9        10  2.197225

In [135]:
df.describe()

valores  val_mas1    val_log
count  10.00000  10.00000  10.000000
mean    5.50000   6.50000   1.510441
std     3.02765   3.02765   0.733024
min     1.00000   2.00000   0.000000
25%     3.25000   4.25000   1.170533
50%     5.50000   6.50000   1.700599
75%     7.75000   8.75000   2.046059
max    10.00000  11.00000   2.302585